export const parentProfile = [
  {
    title: "Father’s Name *",
    name: "fathers_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Mother’s Name *",
    name: "mothers_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Email Address *",
    name: "email",
    placeholder: "Email address",
    rules: [{ required: true, message: "Please input your email!" }],
    type: "text",
  },
  {
    title: "Mobile Number *",
    name: "mobile",
    placeholder: "Mobile Number",
    rules: [{ required: true, message: "Please input your mobile number!" }],
    type: "text",
  },
  {
    title: "Secondary Email",
    name: "secondary_email",
    optional: true,
    rules: [{ required: true, message: "Please input your secondary email!" }],
    type: "text",
  },
  {
    title: "Secondary Mobile Number",
    name: "secondary_mobile",
    optional: true,
    rules: [{ required: true, message: "Please input your secondary mobile!" }],
    type: "text",
  },
  {
    title: "Member of HSNC",
    name: "menever_of_hsnc",
    placeholder: "",
    rules: [{ required: true, message: "Please input your HSNC!" }],
    type: "text",
  },
];
