export const siblingEnrollmentForm = [
  {
    title: "Father’s Name *",
    name: "fathers_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Mother’s Name *",
    name: "mothers_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Student’s First Name *",
    name: "first_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Student’s Last Name *",
    name: "last_name",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "Student's Date of Birth *",
    name: "date_of_birth",
    placeholder: "",
    rules: [{ required: true, message: "Please input your date of birth!" }],
    type: "date",
  },
  {
    title: "Student's School Grade as of Fall 2024*",
    name: "grade_as_of_fall_2024",
    placeholder: "Name",
    rules: [{ required: true, message: "Please select your grade!" }],
    type: "select",
    options: [
      { label: "Grade 1", value: "grade1" },
      { label: "Grade 2", value: "grade2" },
      { label: "Grade 3", value: "grade3" },
      { label: "Grade 4", value: "grade4" },
      { label: "Grade 5", value: "grade5" },
      { label: "Grade 6", value: "grade6" },
      { label: "Grade 7", value: "grade7" },
      { label: "Grade 8", value: "grade8" },
      { label: "Grade 9", value: "grade9" },
      { label: "Grade 10", value: "grade10" },
      { label: "Grade 11", value: "grade11" },
      { label: "Grade 12", value: "grade12" },
    ],
  },
  {
    title: "2nd Student’s First Name *",
    name: "first_name2",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "2nd Student’s Last Name *",
    name: "last_name2",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your name!" }],
    type: "text",
  },
  {
    title: "2nd Student's Date of Birth *",
    name: "date_of_birth2",
    placeholder: "",
    rules: [{ required: true, message: "Please input your date of birth!" }],
    type: "date",
  },
  {
    title: "2nd Student's School Grade as of Fall 2024*",
    name: "grade_as_of_fall_20242",
    placeholder: "Name",
    rules: [{ required: true, message: "Please select your grade!" }],
    type: "select",
    options: [
      { label: "Grade 1", value: "grade1" },
      { label: "Grade 2", value: "grade2" },
      { label: "Grade 3", value: "grade3" },
      { label: "Grade 4", value: "grade4" },
      { label: "Grade 5", value: "grade5" },
      { label: "Grade 6", value: "grade6" },
      { label: "Grade 7", value: "grade7" },
      { label: "Grade 8", value: "grade8" },
      { label: "Grade 9", value: "grade9" },
      { label: "Grade 10", value: "grade10" },
      { label: "Grade 11", value: "grade11" },
      { label: "Grade 12", value: "grade12" },
    ],
  },
  {
    title: "Primary Email Address*",
    name: "student_email_address",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your primary email!" }],
    type: "text",
  },
  {
    title: "Secondary Email Address",
    name: "student_email_address2",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your secondary email!" }],
    type: "text",
  },
  {
    title: "Phone Number",
    name: "student_phone_number",
    placeholder: "Name",
    rules: [{ required: true, message: "Please input your phone number!" }],
    type: "text",
  },
  {
    title: "Preferred Class Time",
    name: "preferred_class_time",
    rules: [{ required: true, message: "Please select your preferred time!" }],
    type: "select",
    options: [
      {
        label: "Morning",
        value: "morning",
      },
      {
        label: "Afternoon",
        value: "afternoon",
      },
      {
        label: "Evening",
        value: "evening",
      },
    ],
  },
  {
    title: "Sibling of current student?",
    name: "sibling_of_current_student",
    rules: [{ required: true, message: "Please select your sibling!" }],
    type: "radio",
    options: [
      {
        label: "Yes",
        value: "yes",
      },
      {
        label: "No",
        value: "no",
      },
    ],
  },
  {
    title: "Comments",
    name: "comments",
    rules: [{ required: true, message: "Please input your comments!" }],
    type: "textarea",
  },
];
