export type GurukulPrayerType = {
  id: number;
  gurukal_id: number | null;
  uploaded_by: number;
  text: string;
  url: string;
  filename: string;
  type: string;
  status: string;
  created_at: string;
  updated_at: string;
  category_id: number;
  gurukal: object | null;
  uploader: {
    id: number;
    primary_email: string;
    secondary_email: string;
    mobile_number: string;
    secondary_mobile_number: string;
    father_name: string;
    mother_name: string;
    father_volunteering: number;
    mother_volunteering: number;
    is_hsnc_member: number;
    address: string | null;
    city: string;
    state: string;
    zip_code: string;
    is_active: number;
    is_payment_done: number;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    otp: string | null;
    otp_expires_at: string | null;
    is_otp_verified: number;
    profile_image: string | null;
    role: string;
    ai_role: string | null;
    ai_key: string | null;
  };
  category: {
    id: number;
    name: string;
    description: string | null;
    status: string;
    created_at: string | null;
    updated_at: string | null;
  };
};
