export type UserType = {
  address: string;
  city: string;
  created_at: string;
  deleted_at: string | null;
  father_activities: object[];
  father_name: string;
  father_volunteering: number;
  id: number;
  is_active: number;
  is_hsnc_member: number;
  is_otp_verified: number;
  is_payment_done: number;
  mobile_number: string;
  mother_activities: object[];
  mother_name: string;
  mother_volunteering: number;
  otp: string | null;
  otp_expires_at: string | null;
  primary_email: string;
  profile_image: string | null;
  secondary_email: string;
  secondary_mobile_number: string;
  state: string;
  students: object[];
  updated_at: string;
  zip_code: string;
};
